server:
  port: 7091
  servlet:
    context-path: /

spring:
  datasource:
    # mysql5.x 配置，高版本需要加useSSL=false
    #url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&useSSL=false
    # mysql8.0 需要加&useSSL=false&serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/DB?zeroDateTimeBehavior=convertToNull&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    # mysql8.0 驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    # mysql5.x 驱动
    #driver-class-name: com.mysql.jdbc.Driver
    debug: false
    #Druid#
    name: test
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  redis:
    host: 127.0.0.1
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 100ms


#  rabbitmq:
#    host: 127.0.0.1  #mq服务器ip,默认为localhost
#    port: 5672          #mq服务器port,默认为5672
#    username: guest     #mq服务器username,默认为gust
#    password: guest     #mq服务器password,默认为guest
#    virtual-host: /
#    #publisher-confirms: true
#    #消费消息的时候,就必须手动ack确认,不然消息永远还在队列中
#    listener:
#      simple:
#        acknowledge-mode: manual
#      direct:
#        acknowledge-mode: manual

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mappers/**/*Mapper.xml
  global-config:
    # 逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: 1
      # 删除后
      logic-delete-value: 0

